language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - openjdk7
sudo: false
install: true
env:
  - MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
script: mvn -q test -PreducedMemory
after_success:
  - bash <(curl -s https://codecov.io/bash)